[project]
channels = ["conda-forge"]
name = "tomopy-env"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
tomopy = ">=1.12.1,<2"
libtomo = { version = "*", build = "cuda*" }
astra-toolbox = ">=2.3.1,<3"
jupyterlab = ">=4.5.0,<5"
h5py = ">=3.15.1,<4"