on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  list-changed-directories:
    runs-on: ubuntu-latest

    outputs:
      changed-directories: ${{ steps.list-changed-directories.outputs.changed-directories }}

    steps:
      - uses: actions/checkout@v4
      - uses: sankichi92/list-changed-directories@v1
        id: list-changed-directories
        with:
          target-file: Dockerfile

  test:
    needs: list-changed-directories
    if: needs.list-changed-directories.outputs.changed-directories != '[]'

    strategy:
      matrix:
        working-directory: ${{ fromJSON(needs.list-changed-directories.outputs.changed-directories) }}
      uses: ./.github/workflows/_container.yml
      with:
        working-directory: ${{ matrix.working-directory }}

    # steps:
    #   - uses: actions/checkout@v4
    #   - name: Bump version and push tag
    #     id: tag_version
    #     uses: mathieudutour/github-tag-action@v6.2
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       dry_run: true
    #       tag_prefix: ${{ matrix.working-directory }}/v
    #   - name: echo tag
    #     working-directory: ./${{ matrix.working-directory }}
    #     run: |
    #       echo $PWD
    #       echo ${{ steps.tag_version.outputs.new_tag }}
    #       echo ${{ steps.tag_version.outputs.new_version }}
