on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  list-changed-directories:
    runs-on: ubuntu-latest

    outputs:
      changed-directories: ${{ steps.list-changed-directories.outputs.changed-directories }}

    steps:
      - uses: actions/checkout@v4

      - uses: sankichi92/list-changed-directories@v1
        id: list-changed-directories
        with:
          target-file: Dockerfile

  test:
    needs: list-changed-directories
    if: needs.list-changed-directories.outputs.changed-directories != '[]'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        working-directory: ${{ fromJSON(needs.list-changed-directories.outputs.changed-directories) }}

    steps:
      - uses: actions/checkout@v4
      - run: bundle exec rake
        working-directory: ${{ matrix.working-directory }}

      - name: Install dependencies
        run: |
          echo ${{ matrix.working-directory }}